etc-git: normalize option with evomaintenance

diff --git a/etc-git/files/ansible-commit b/etc-git/files/ansible-commit
--- a/etc-git/files/ansible-commit
+++ b/etc-git/files/ansible-commit
@@ -31,7 +31,7 @@ Usage: ansible-commit --message "add new host"
 
 Options
      --message MESSAGE        set the commit message
-     --only-path PATH         commit only files matching PATH
+     --commit-only-path PATH  commit only files matching PATH
                               can be set multiple times
                               can contain globs (compatible with find)
      --no-lxc                 disable commit inside LXC containers
@@ -42,10 +42,10 @@ Options
      --only-etc               commit only inside /etc
      --only-etc-bind          commit only inside /etc/bind
      --only-usr-share-scripts commit only inside /usr/share/scripts
- -V, --version                print version number
  -v, --verbose                increase verbosity
  -n, --dry-run                actions are not executed
  -h, --help                   print this message and exit
+ -V, --version                print version number
 END
 }
 
@@ -78,9 +78,9 @@ main() {
     set -f
 
     # pass the filters "as is", if any
-    if [ -n "${ONLY_PATH}" ]; then
-        for path in ${ONLY_PATH}; do
-            common_args="${common_args} --only-path ${path}"
+    if [ -n "${COMMIT_ONLY_PATH}" ]; then
+        for path in ${COMMIT_ONLY_PATH}; do
+            common_args="${common_args} --commit-only-path ${path}"
         done
     fi
 
@@ -143,7 +143,7 @@ LXC=1
 ETC=1
 ETC_BIND=1
 USR_SHARE_SCRIPTS=1
-ONLY_PATH=""
+COMMIT_ONLY_PATH=""
 MESSAGE=""
 
 # Parse options
@@ -213,27 +213,27 @@ while :; do
             ETC_BIND=0
             USR_SHARE_SCRIPTS=1
             ;;
-        --only-path)
+        --commit-only-path)
             # message options, with value separated by space
             if [ -n "$2" ]; then
                 set -f
-                ONLY_PATH="$(append_path "${ONLY_PATH}" "$2")"
+                COMMIT_ONLY_PATH="$(append_path "${COMMIT_ONLY_PATH}" "$2")"
                 set +f
                 shift
             else
-                printf 'ERROR: "--only-path" requires a non-empty option argument.\n' >&2
+                printf 'ERROR: "--commit-only-path" requires a non-empty option argument.\n' >&2
                 exit 1
             fi
             ;;
-        --only-path=?*)
+        --commit-only-path=?*)
             # message options, with value separated by =
             set -f
-            ONLY_PATH="$(append_path "${ONLY_PATH}" "${1#*=}")"
+            COMMIT_ONLY_PATH="$(append_path "${COMMIT_ONLY_PATH}" "${1#*=}")"
             set +f
             ;;
-        --only-path=)
+        --commit-only-path=)
             # message options, without value
-            printf 'ERROR: "--only-path" requires a non-empty option argument.\n' >&2
+            printf 'ERROR: "--commit-only-path" requires a non-empty option argument.\n' >&2
             exit 1
             ;;
         -n|--dry-run)
diff --git a/etc-git/files/evocommit b/etc-git/files/evocommit
--- a/etc-git/files/evocommit
+++ b/etc-git/files/evocommit
@@ -30,16 +30,15 @@ show_usage() {
 Usage: evocommit --repository /path/to/repository --message "add new host"
 
 Options
-     --repository PATH   set the path for the repository
-     --message MESSAGE   set the commit message
-     --only-path PATH    add only this path to the commit
-                         can be set multiple times
-                         can contain globs
- -V, --version           print version number
- -v, --verbose           increase verbosity
- -n, --dry-run           actions are not executed
-     --help              print this message and exit
-     --version           print version and exit
+ --repository PATH        set the path for the repository
+ --message MESSAGE        set the commit message
+ --commit-only-path PATH  add only this path to the commit
+                          can be set multiple times
+                          can contain globs
+ -v, --verbose            increase verbosity
+ -n, --dry-run            actions are not executed
+ -h, --help               print this message and exit
+ -V, --version            print version number
 END
 }
 
@@ -133,10 +132,10 @@ main() {
 
             # find and "git add" all existing paths in the repository
             # that match the filter (if present)
-            if [ -n "${ONLY_PATH}" ]; then
+            if [ -n "${COMMIT_ONLY_PATH}" ]; then
                 # disable globbing
                 set -f
-                for path in ${ONLY_PATH}; do
+                for path in ${COMMIT_ONLY_PATH}; do
                     # shellcheck disable=SC2086
                     ${GIT_BIN} add "${path}" 2>/dev/null
                 done
@@ -191,7 +190,7 @@ main() {
 DRY_RUN=0
 VERBOSE=0
 ANSIBLE=0
-ONLY_PATH=""
+COMMIT_ONLY_PATH=""
 MESSAGE=""
 
 # Parse options
@@ -244,23 +243,23 @@ while :; do
             printf 'ERROR: "--repository" requires a non-empty option argument.\n' >&2
             exit 1
             ;;
-        --only-path)
+        --commit-only-path)
             # message options, with value speparated by space
             if [ -n "$2" ]; then
-                ONLY_PATH="$(append_path "${ONLY_PATH}" "$2")"
+                COMMIT_ONLY_PATH="$(append_path "${COMMIT_ONLY_PATH}" "$2")"
                 shift
             else
-                printf 'ERROR: "--only-path" requires a non-empty option argument.\n' >&2
+                printf 'ERROR: "--commit-only-path" requires a non-empty option argument.\n' >&2
                 exit 1
             fi
             ;;
-        --only-path=?*)
+        --commit-only-path=?*)
             # message options, with value speparated by =
-            ONLY_PATH="$(append_path "${ONLY_PATH}" "${1#*=}")"
+            COMMIT_ONLY_PATH="$(append_path "${COMMIT_ONLY_PATH}" "${1#*=}")"
             ;;
-        --only-path=)
+        --commit-only-path=)
             # message options, without value
-            printf 'ERROR: "--only-path" requires a non-empty option argument.\n' >&2
+            printf 'ERROR: "--commit-only-path" requires a non-empty option argument.\n' >&2
             exit 1
             ;;
         -n|--dry-run)
