autosysadmin-agent: remove restart_nrpe (deployed separately) and add examples

diff --git a/autosysadmin-agent/files/upstream/restart/examples/restart_keepalived b/autosysadmin-agent/files/upstream/restart/examples/restart_keepalived
--- a/autosysadmin-agent/files/upstream/restart/examples/restart_keepalived
+++ b/autosysadmin-agent/files/upstream/restart/examples/restart_keepalived
@@ -5,7 +5,7 @@ source "${AUTOSYSADMIN_LIB}/common.sh"  || exit 1
 source "${AUTOSYSADMIN_LIB}/restart.sh" || exit 1
 
 # shellcheck disable=SC2034
-RUNNING="nwh-fr"
+RUNNING="always"
 
 ## Possible values for RUNNING :
 ##   never    => disabled
@@ -15,34 +15,14 @@ RUNNING="nwh-fr"
 ##   custom   => enabled if `running_custom()` function returns 0, otherwise disabled.
 
 ## The name of the service, mainly for logging
-service_name="nagios-nrpe-server"
-## The SysVinit script name
-sysvinit_script="${service_name}"
+service_name="hapee-extras-vrrp"
 ## The systemd service name
 systemd_service="${service_name}.service"
 
-is_service_alive() {
-    ## this must return 0 if the service is alive, otherwise return 1
-    ## Example:
-    pgrep -u nagios nrpe > /dev/null
-}
+is_ping_ok() {
+    /usr/lib/nagios/plugins/check_ping -H "$1" -w 2,20% -c 5,50% > /dev/null
 
-## Action for SysVinit system
-sysvinit_action() {
-    # Save service status before restart
-    timeout 2 "/etc/init.d/${sysvinit_script}" status | save_in_log_dir "${service_name}.before.status"
-
-    # Try to restart
-    timeout 20 "/etc/init.d/${sysvinit_script}" restart > /dev/null
-    rc=$?
-    if [ "${rc}" -eq "0" ]; then
-        log_action "Restart ${service_name}: OK"
-    else
-        log_action "Restart ${service_name}: failed"
-    fi
-
-    # Save service status after restart
-    timeout 2 "/etc/init.d/${sysvinit_script}" status | save_in_log_dir "${service_name}.after.status"
+    test $? -ge 2
 }
 
 ## Action for systemd system
@@ -77,29 +57,59 @@ if is_service_alive; then
     exit 0
 fi
 
-# Yes we do, so check for sysvinit or systemd
-if is_systemd; then
-    if ! is_systemd_enabled "${systemd_service}"; then
-        # log_global "${service_name} is disabled (or missing), nothing left to do."
-        exit 0
-    fi
-    if is_systemd_active "${systemd_service}"; then
-        # log_global "${service_name} is active, nothing left to do."
-        exit 0
-    fi
 
-    # Let's finally do the action
-    pre_restart
-    systemd_action
-    post_restart
-else
-    if ! is_sysvinit_enabled "*${sysvinit_script}*"; then
-        # log_global "${service_name} not enabled. Aborting"
-        exit 0
-    fi
-
-    # Let's finally do the action
-    pre_restart
-    sysvinit_action
-    post_restart
+if ! is_systemd_enabled "${systemd_service}"; then
+    # log_global "${service_name} is disabled (or missing), nothing left to do."
+    exit 0
 fi
+# if is_systemd_active "${systemd_service}"; then
+#     # log_global "${service_name} is active, nothing left to do."
+#     exit 0
+# fi
+
+# Let's finally do the action
+pre_restart
+
+
+
+vip="54.37.170.194"
+
+vip_peer1="delubac-delupay-pp-lb00"
+wan_ip1="54.37.170.195"
+lan_ip1="172.19.1.20"
+
+vip_peer2="delubac-delupay-pp-lb01"
+wan_ip2="54.37.170.196"
+lan_ip2="172.19.1.21"
+
+if ! is_ping_ok "${vip}"; then
+
+    if is_ping_ok "${wan_ip1}"; then
+        ssh "${lan_ip1}" -t "systemctl restart ${systemd_service}"
+        rc=$?
+        if [ "${rc}" -eq "0" ]; then
+            log_action "Restart ${service_name} on ${vip_peer1}: OK"
+        else
+            log_action "Restart ${service_name} on ${vip_peer1}: failed"
+        fi
+    fi
+fi
+
+sleep 2
+
+if ! is_ping_ok "${vip}"; then
+
+    if is_ping_ok "${wan_ip2}"; then
+        ssh "${lan_ip2}" -t "systemctl restart ${systemd_service}"
+        rc=$?
+        if [ "${rc}" -eq "0" ]; then
+            log_action "Restart ${service_name} on ${vip_peer2}: OK"
+        else
+            log_action "Restart ${service_name} on ${vip_peer2}: failed"
+        fi
+    fi
+fi
+
+
+
+post_restart
diff --git a/autosysadmin-agent/files/upstream/restart/examples/restart_redis b/autosysadmin-agent/files/upstream/restart/examples/restart_redis
--- a/autosysadmin-agent/files/upstream/restart/examples/restart_redis
+++ b/autosysadmin-agent/files/upstream/restart/examples/restart_redis
@@ -5,7 +5,7 @@ source "${AUTOSYSADMIN_LIB}/common.sh"  || exit 1
 source "${AUTOSYSADMIN_LIB}/restart.sh" || exit 1
 
 # shellcheck disable=SC2034
-RUNNING="nwh-fr"
+RUNNING="always"
 
 ## Possible values for RUNNING :
 ##   never    => disabled
@@ -15,16 +15,23 @@ RUNNING="nwh-fr"
 ##   custom   => enabled if `running_custom()` function returns 0, otherwise disabled.
 
 ## The name of the service, mainly for logging
-service_name="nagios-nrpe-server"
+service_name="redis"
 ## The SysVinit script name
 sysvinit_script="${service_name}"
 ## The systemd service name
 systemd_service="${service_name}.service"
 
 is_service_alive() {
-    ## this must return 0 if the service is alive, otherwise return 1
-    ## Example:
-    pgrep -u nagios nrpe > /dev/null
+    uuid="autosysadmin-restart-redis-$(dbus-uuidgen)"
+
+    timeout 10 redis-cli set "$uuid" "$uuid" 2>&1 > /dev/null
+    rc=$?
+    timeout 10 redis-cli get "$uuid" 2>&1 > /dev/null
+    rc=$(($? > 0 ? $? : rc))
+    timeout 10 redis-cli del "$uuid" 2>&1 > /dev/null
+    rc=$(($? > 0 ? $? : rc))
+
+    return $rc
 }
 
 ## Action for SysVinit system
@@ -78,7 +85,17 @@ if is_service_alive; then
 fi
 
 # Yes we do, so check for sysvinit or systemd
-if is_systemd; then
+if is_debian_version "8" "<="; then
+    if ! is_sysvinit_enabled "*${sysvinit_script}*"; then
+        # log_global "${service_name} not enabled. Aborting"
+        exit 0
+    fi
+
+    # Let's finally do the action
+    pre_restart
+    sysvinit_action
+    post_restart
+else
     if ! is_systemd_enabled "${systemd_service}"; then
         # log_global "${service_name} is disabled (or missing), nothing left to do."
         exit 0
@@ -91,15 +108,5 @@ if is_systemd; then
     # Let's finally do the action
     pre_restart
     systemd_action
-    post_restart
-else
-    if ! is_sysvinit_enabled "*${sysvinit_script}*"; then
-        # log_global "${service_name} not enabled. Aborting"
-        exit 0
-    fi
-
-    # Let's finally do the action
-    pre_restart
-    sysvinit_action
     post_restart
 fi
diff --git a/autosysadmin-agent/files/upstream/restart/examples/zzz-restart_example.template b/autosysadmin-agent/files/upstream/restart/examples/zzz-restart_example.template
--- a/autosysadmin-agent/files/upstream/restart/examples/zzz-restart_example.template
+++ b/autosysadmin-agent/files/upstream/restart/examples/zzz-restart_example.template
@@ -14,8 +14,23 @@ RUNNING="nwh-fr"
 ##   nwh-ca   => enabled during non-working-hours in Canada (not supported yet)
 ##   custom   => enabled if `running_custom()` function returns 0, otherwise disabled.
 
+## Uncomment and customize this method if you want to have a special logic :
+##
+##   return 1 if we should not run
+##   return 0 if we should run
+##
+## Some available functions :
+##   is_weekend()  : Saturday or Sunday
+##   is_holiday()  : holiday in France (based on `gcal(1)`)
+##   is_workday()  : not weekend and not holiday
+##   is_worktime() : work day between 9-12h and 14-18h
+#
+# running_custom() {
+#     # implement your own custom method to decide if we should run or not
+# }
+
 ## The name of the service, mainly for logging
-service_name="nagios-nrpe-server"
+service_name="example"
 ## The SysVinit script name
 sysvinit_script="${service_name}"
 ## The systemd service name
@@ -24,7 +39,7 @@ systemd_service="${service_name}.service"
 is_service_alive() {
     ## this must return 0 if the service is alive, otherwise return 1
     ## Example:
-    pgrep -u nagios nrpe > /dev/null
+    pgrep -u USER PROCESS_NAME > /dev/null
 }
 
 ## Action for SysVinit system
@@ -78,7 +93,17 @@ if is_service_alive; then
 fi
 
 # Yes we do, so check for sysvinit or systemd
-if is_systemd; then
+if is_debian_version "8" "<="; then
+    if ! is_sysvinit_enabled "*${sysvinit_script}*"; then
+        # log_global "${service_name} not enabled. Aborting"
+        exit 0
+    fi
+
+    # Let's finally do the action
+    pre_restart
+    sysvinit_action
+    post_restart
+else
     if ! is_systemd_enabled "${systemd_service}"; then
         # log_global "${service_name} is disabled (or missing), nothing left to do."
         exit 0
@@ -91,15 +116,5 @@ if is_systemd; then
     # Let's finally do the action
     pre_restart
     systemd_action
-    post_restart
-else
-    if ! is_sysvinit_enabled "*${sysvinit_script}*"; then
-        # log_global "${service_name} not enabled. Aborting"
-        exit 0
-    fi
-
-    # Let's finally do the action
-    pre_restart
-    sysvinit_action
     post_restart
 fi
