debug, amélioration complétion

diff --git a/nagios-nrpe/files/alerts_switch b/nagios-nrpe/files/alerts_switch
--- a/nagios-nrpe/files/alerts_switch
+++ b/nagios-nrpe/files/alerts_switch
@@ -4,8 +4,6 @@
 # https://gitea.evolix.org/evolix/ansible-roles/src/branch/stable/nagios-nrpe
 #
 
-set -e
-
 readonly PROGNAME=$(basename $0)
 readonly base_dir="/var/lib/monitoringctl"
 readonly log_file="/var/log/monitoringctl.log"
@@ -41,28 +39,32 @@ time_to_seconds() {
     # $1: time in string format
     if echo "${1}" | grep -E -q '^([0-9]+[wdhms])+$'; then
         echo "${1}" | sed 's/w/ * 604800 + /g; s/d/ * 86400 + /g; s/h/ * 3600 + /g; s/m/ * 60 + /g; s/s/ + /g; s/+ $//' | xargs expr
-    elif echo "${1}" | grep -E -q '^([0-9]+$)'; then
-        echo "${1} * 3600" | xargs expr
+    elif echo "${1}" | grep -E -q '^([0-9]+h[0-9]+$)'; then
+        echo "${1}" | sed 's/h/ * 3600 + /g; s/$/ * 60/' | xargs expr
+    elif echo "${1}" | grep -E -q '^([0-9]+m[0-9]+$)'; then
+        echo "${1}" | sed 's/m/ * 60 + /g' | xargs expr
     else
         error "Invalid duration: '${1}'."
     fi
 }
 
 get_disable_names() {
-    grep "alerts_wrapper" -Rs /etc/nagios/ | grep -vE "^\s*#" | awk '{ for (i=1; i<=NF; i++) { if ($i ~ /(-n|--name)/) print $(i+1) } }' | tr ',' '\n' | sort | uniq
+    grep "alerts_wrapper" -Rs /etc/nagios/ | grep -vE "^\s*#" | awk '{ for (i=1; i<=NF; i++) { if ($i ~ /^(-n|--name)$/) { print $(i+1); break } } }' | tr ',' '\n' | sort | uniq
 }
 
 disable_alerts () {
-    # $1: check name
-    disable_file_path="${base_dir}/${check_name}_alerts_disabled"
-    echo "${duration_sec}" > "${disable_file_path}"
+    # $1: check name, $2: duration_sec
+    now_secs=$(date +"%s")
+    disable_until_secs=$(( now_secs + $2 ))
+    disable_file_path="${base_dir}/${1}_alerts_disabled"
+    echo "${disable_until_secs}" > "${disable_file_path}"
     chmod 0644 "${disable_file_path}"
     log_disable "$1"
 }
 
 enable_alerts () {
     # $1: check name
-    disable_file_path="${base_dir}/${check_name}_alerts_disabled"
+    disable_file_path="${base_dir}/${1}_alerts_disabled"
     if [ -e "${disable_file_path}" ]; then
         rm "${disable_file_path}"
     fi
@@ -85,18 +87,25 @@ log_enable () {
 
 
 main () {
-    mkdir -p "${base_dir}"
-
-    #TODO
-    if all
-        for check in $(get_disable_names); do
-        done
+    install --mode=0755 --directory "${base_dir}"
 
     if [ "${action}" == 'enable' ]; then
-        enable_alerts "${check_name}"
+        if [ "${check_name}" == "all" ]; then
+            for check in $(get_disable_names); do
+                enable_alerts "${check}"
+            done
+        else
+            enable_alerts "${check_name}"
+        fi
     elif [ "${action}" == 'disable' ]; then
         duration_sec=$(time_to_seconds "${duration}")
-        disable_alerts "${check_name}"
+        if [ "${check_name}" == "all" ]; then
+            for check in $(get_disable_names); do
+                disable_alerts "${check}" "${duration_sec}"
+            done
+        else
+            disable_alerts "${check_name}" "${duration_sec}"
+        fi
     elif [ "${action}" == 'help' ]; then
         usage
     fi
@@ -116,20 +125,22 @@ while :; do
             fi
             shift; shift;;
         *)
-            if [ -z "${action}" ]; then
-                error "Missing action argument."
-            elif [ -n "${check_name}" ]; then
-                error "Unknown argument '$1'."
-            elif [ -z "$1" ]; then
-                break
-            fi
-            get_disable_names | grep --quiet -E "^$1$"
-            arg_is_in_disable_names_rc=$?
-            if [ "${arg_is_in_disable_names_rc}" -eq 0 ] || [ "$1" == "all" ]; then
-                check_name="$1"
+            if [ -n "$1" ]; then
+                get_disable_names | grep --quiet -E "^$1$"
+                arg_is_in_disable_names_rc=$?
+                if [ "${arg_is_in_disable_names_rc}" -eq 0 ] || [ "$1" == "all" ]; then
+                    check_name="$1"
+                else
+                    error "Unknown argument '$1', or NAME not defined in NRPE configuration."
+                fi
             else
-                error "Unknown argument '$1', or NAME not defined in NRPE configuration."
+                if [ -z "${action}" ]; then
+                    error "Missing action argument."
+                elif [ -z "$1" ]; then
+                    break
+                fi
             fi
+
             shift;;
     esac
 done
diff --git a/nagios-nrpe/files/alerts_wrapper b/nagios-nrpe/files/alerts_wrapper
--- a/nagios-nrpe/files/alerts_wrapper
+++ b/nagios-nrpe/files/alerts_wrapper
@@ -55,7 +55,7 @@ time_to_seconds() {
 
 delay_from_disable_file() {
     # $1: disabled file containing the re-enable time in sec
-    enable_secs=$(grep -v -E "^\s*#" "${1}" | grep -E "[0-9]+" | head -n1 | awk '{print $1}')
+    enable_secs=$(grep -v -E "^\s*#" "${1}" | grep -E "^[0-9]+$" | head -n1 | awk '{print $1}')
     # If file is empty, use file last change date plus default disabled time
     if [ -z "${enable_secs}" ]; then
         file_last_change_secs=$(stat -c %Z "$1")
@@ -71,19 +71,19 @@ delay_to_string() {
     #$1 delay in secs
     delay_days="$(( delay /86400 ))"
     if [ "${delay_days}" -eq 0 ]; then delay_days=""
-    else delay_days="${delay_days}d "; fi
+    else delay_days="${delay_days}d"; fi
 
     delay_hours="$(( (delay %86400) /3600 ))"
     if [ "${delay_hours}" -eq 0 ]; then delay_hours=""
-    else delay_hours="${delay_hours}h "; fi
+    else delay_hours="${delay_hours}h"; fi
 
     delay_minutes="$(( ((delay %86400) %3600) /60 ))"
     if [ "${delay_minutes}" -eq 0 ]; then delay_minutes=""
-    else delay_minutes="${delay_minutes}m "; fi
+    else delay_minutes="${delay_minutes}m"; fi
 
     delay_seconds="$(( ((delay %86400) %3600) %60 ))"
     if [ "${delay_seconds}" -eq 0 ]; then delay_seconds=""
-    else delay_days="${delay_days}s "; fi
+    else delay_seconds="${delay_seconds}s"; fi
 
     echo "${delay_days}${delay_hours}${delay_minutes}${delay_seconds}"
 }
@@ -120,7 +120,7 @@ main() {
         timeout_command="timeout 9"
     fi
 
-    check_stdout=$(${timeout_command} "${check_command}")
+    check_stdout=$(${timeout_command} ${check_command})
     check_rc=$?
 
     if [ "${is_disabled}" == "True" ] && [ "${check_rc}" -eq 124 ] && [ -z "${check_stdout}" ]; then
@@ -130,10 +130,10 @@ main() {
     if [ "${is_disabled}" == "True" ]; then
         delay=$(delay_from_disable_file "${disable_file}")
         delay_str="$(delay_to_string "${delay}")"
-        echo "ALERTS DISABLED for ${check_name} until ${delay_str}."
+        echo "ALERT DISABLED until ${delay_str} - ${check_stdout}"
+    else
+        echo "${check_stdout}"
     fi
-
-    echo "${check_stdout}"
 
     if [ "${is_disabled}" == "True" ]; then
         if [ ${check_rc} = 0 ]; then
@@ -179,7 +179,6 @@ if [[ "${1}" =~ -.* ]]; then
                 printf 'ERROR: "--name" requires a non-empty option argument.\n' >&2
                 exit 1
                 ;;
-
             --)
                 # End of all options.
                 shift
@@ -210,11 +209,15 @@ fi
 
 if [ -z "${check_name}" ]; then
     printf 'ERROR: You must specify a check name, with --names.\n' >&2
-    exit 1
+    exit 2
 fi
 if [ -z "${check_command}" ]; then
     printf 'ERROR: You must specify a command to execute.\n' >&2
-    exit 1
+    exit 2
+fi
+if [ -e "${base_dir}" ] && [ ! -x "${base_dir}" ]; then
+    printf "ERROR: %s exists but is no reachable.\n" "${base_dir}"
+    exit 2
 fi
 
 readonly check_name
