Commit

diff --git a/nagios-nrpe/files/alerts_switch b/nagios-nrpe/files/alerts_switch
--- a/nagios-nrpe/files/alerts_switch
+++ b/nagios-nrpe/files/alerts_switch
@@ -5,21 +5,27 @@
 #
 
 readonly PROGNAME=$(basename $0)
-readonly base_dir="/var/lib/monitoringctl"
-readonly log_file="/var/log/monitoringctl.log"
+readonly VERSION="24.04.00"
 
-# Default disable duration
-duration="1h"
+# Load common functions and vars
+readonly lib_dir="/usr/local/lib/monitoringctl"
+if [ -r "${lib_dir}/common" ]; then
+    # shellcheck source=monitoringctl_common
+    source "${lib_dir}/common"
+else
+    >&2 echo "Error: missing ${lib_dir}/common file."
+    exit 1
+fi
 
-usage() {
+function show_help() {
     cat <<END
 $PROGNAME disables or enables NRPE alerts wrapped by the script 'alerts_wrapper' in NRPE configuration.
 
-Usage: $PROGNAME disable [-d|--during <DURATION>] <CHECK_NAME|ALL>
-       $PROGNAME enable <CHECK_NAME|ALL>
+Usage: $PROGNAME disable [-d|--during <DURATION>] <WRAPPER_NAME|all>
+       $PROGNAME enable <WRAPPER_NAME|all>
        $PROGNAME help
 
-CHECK_NAME: the name given to '--name' option of 'alerts_wrapper'.
+WRAPPER_NAME: The name given to '--name' option of 'alerts_wrapper'.
 DURATION: Duration of alert disabling.
           Can be '1d' for 1 day, '5m' for 5 minutes or more complex
           expressions like '1w2d10m42s' (if no time unit is provided,
@@ -28,115 +34,78 @@ DURATION: Duration of alert disabling.
 END
 }
 
-error() {
-    # $1: error message
-    >&2 echo "$1"
-    usage
-    exit 1
-}
-
-time_to_seconds() {
-    # $1: time in string format
-    if echo "${1}" | grep -E -q '^([0-9]+[wdhms])+$'; then
-        echo "${1}" | sed 's/w/ * 604800 + /g; s/d/ * 86400 + /g; s/h/ * 3600 + /g; s/m/ * 60 + /g; s/s/ + /g; s/+ $//' | xargs expr
-    elif echo "${1}" | grep -E -q '^([0-9]+h[0-9]+$)'; then
-        echo "${1}" | sed 's/h/ * 3600 + /g; s/$/ * 60/' | xargs expr
-    elif echo "${1}" | grep -E -q '^([0-9]+m[0-9]+$)'; then
-        echo "${1}" | sed 's/m/ * 60 + /g' | xargs expr
-    else
-        error "Invalid duration: '${1}'."
-    fi
-}
-
-get_disable_names() {
-    grep "alerts_wrapper" -Rs /etc/nagios/ | grep -vE "^\s*#" | awk '{ for (i=1; i<=NF; i++) { if ($i ~ /^(-n|--name)$/) { print $(i+1); break } } }' | tr ',' '\n' | sort | uniq
-}
-
-disable_alerts () {
-    # $1: check name, $2: duration_sec
+function disable_alerts() {
+    # $1: wrapper name, $2: duration_sec
     now_secs=$(date +"%s")
-    disable_until_secs=$(( now_secs + $2 ))
-    disable_file_path="${base_dir}/${1}_alerts_disabled"
+    disable_until_secs=$(( now_secs + ${2} ))
+    disable_file_path="$(get_disable_file_path "${1}")"
     echo "${disable_until_secs}" > "${disable_file_path}"
     chmod 0644 "${disable_file_path}"
-    log_disable "$1"
+    log "${1} alerts disabled by $(logname || echo unknown)"
 }
 
-enable_alerts () {
-    # $1: check name
-    disable_file_path="${base_dir}/${1}_alerts_disabled"
+function enable_alerts() {
+    # $1: wrapper name
+    disable_file_path="$(get_disable_file_path "${1}")"
     if [ -e "${disable_file_path}" ]; then
         rm "${disable_file_path}"
     fi
-    log_enable "$1"
+    log "${1} alerts enabled by $(logname || echo unknown)"
 }
 
-now () {
-  date --iso-8601=seconds
-}
-
-log_disable () {
-    # $1: check name
-    echo "$(now) - alerts_switch: $1 alerts disabled by $(logname || echo unknown)" >> $log_file
-}
-
-log_enable () {
-    # $1: check name
-    echo "$(now) - alerts_switch: $1 alerts enabled by $(logname || echo unknown)" >> $log_file
-}
-
-
-main () {
-    install --mode=0755 --directory "${base_dir}"
+function main() {
+    install --mode=0755 --directory "${var_dir}"
 
     if [ "${action}" == 'enable' ]; then
-        if [ "${check_name}" == "all" ]; then
-            for check in $(get_disable_names); do
-                enable_alerts "${check}"
+        if [ "${wrapper_name}" == "all" ]; then
+            for wrapper in $(get_wrappers_names); do
+                enable_alerts "${wrapper}"
             done
         else
-            enable_alerts "${check_name}"
+            enable_alerts "${wrapper_name}"
         fi
     elif [ "${action}" == 'disable' ]; then
         duration_sec=$(time_to_seconds "${duration}")
-        if [ "${check_name}" == "all" ]; then
-            for check in $(get_disable_names); do
-                disable_alerts "${check}" "${duration_sec}"
+        if [ "${wrapper_name}" == "all" ]; then
+            for wrapper in $(get_wrappers_names); do
+                disable_alerts "${wrapper}" "${duration_sec}"
             done
         else
-            disable_alerts "${check_name}" "${duration_sec}"
+            disable_alerts "${wrapper_name}" "${duration_sec}"
         fi
     elif [ "${action}" == 'help' ]; then
-        usage
+        show_help
     fi
 }
 
 
 while :; do
-    case "$1" in
+    case "${1}" in
         enable|disable|help)
-            action="$1"
+            action="${1}"
             shift;;
         -d|--during)
             if [ "$#" -gt 1 ]; then
-                duration="$2"
+                if filter_duration "${2}"; then
+                    duration="${2}"
+                else
+                    usage_error "Option --during: \"${2}\" is not a valid duration."
+                fi
             else
                 error "Missing --during argument."
             fi
             shift; shift;;
         *)
-            if [ -n "$1" ]; then
-                get_disable_names | grep --quiet -E "^$1$"
-                arg_is_in_disable_names_rc=$?
-                if [ "${arg_is_in_disable_names_rc}" -eq 0 ] || [ "$1" == "all" ]; then
-                    check_name="$1"
+            if [ -n "${1}" ]; then
+                if is_wrapper "${1}" || [ "${1}" == "all" ]; then
+                    wrapper_name="${1}"
                 else
-                    error "Unknown argument '$1', or NAME not defined in NRPE configuration."
+                    error "Unknown argument '${1}', or NAME not defined in NRPE configuration."
                 fi
             else
                 if [ -z "${action}" ]; then
                     error "Missing action argument."
-                elif [ -z "$1" ]; then
+                elif [ -z "${1}" ]; then
                     break
                 fi
             fi
@@ -145,13 +114,15 @@ while :; do
     esac
 done
 
-if [ -z "${check_name}" ] && [ "${action}" != 'help' ] ; then
-    error "Missing CHECK_NAME argument."
+if [ -z "${wrapper_name}" ] && [ "${action}" != 'help' ] ; then
+    error "Missing WRAPPER_NAME."
 fi
 
-readonly check_name
-readonly duration
-readonly action
+if [ -z "${duration}" ]; then
+    duration="${default_disabled_time}"
+fi
+
+readonly wrapper_name duration action
 
 main
 
diff --git a/nagios-nrpe/files/alerts_wrapper b/nagios-nrpe/files/alerts_wrapper
--- a/nagios-nrpe/files/alerts_wrapper
+++ b/nagios-nrpe/files/alerts_wrapper
@@ -4,123 +4,56 @@
 # https://gitea.evolix.org/evolix/ansible-roles/src/branch/stable/nagios-nrpe
 #
 
-readonly VERSION="21.04"
+readonly PROGNAME=$(basename $0)
+readonly VERSION="24.04.00"
 
-# Location of disable files
-readonly base_dir="/var/lib/monitoringctl"
+# Load common functions and vars
+readonly lib_dir="/usr/local/lib/monitoringctl"
+if [ -r "${lib_dir}/common" ]; then
+    # shellcheck source=monitoringctl_common
+    source "${lib_dir}/common"
+else
+    >&2 echo "Error: missing ${lib_dir}/common file."
+    exit 1
+fi
 
-# If no datetime is found in file, this value is used
-readonly default_disabled_time="1d"
-
-
-show_version() {
-    cat <<END
-alerts_wrapper version ${VERSION}
-
-Copyright 2018-2021 Evolix <info@evolix.fr>,
-                    Jérémy Lecour <jlecour@evolix.fr>
-                    and others.
-
-alerts_wrapper comes with ABSOLUTELY NO WARRANTY.This is free software,
-and you are welcome to redistribute it under certain conditions.
-See the GNU General Public License v3.0 for details.
-END
-}
-
-show_help() {
+function show_help() {
     cat <<END
 alerts_wrapper wraps an NRPE command and overrides the return code.
 
-Usage: alerts_wrapper --name <CHECK_NAME> <CHECK_COMMAND>
-Usage: alerts_wrapper <CHECK_NAME> <CHECK_COMMAND> (deprecated)
+Usage: alerts_wrapper --name <WRAPPER_NAME> <CHECK_COMMAND>
+Usage: alerts_wrapper <WRAPPER_NAME> <CHECK_COMMAND> (deprecated)
 
 Options
-  --name               Check name (like load, disk1…)
+  --name               Wrapper name, it is very recommended to use the check name (like load, disk1…).
                        Special name: 'all' is already hard-coded.
   -h, --help           Print this message and exit.
   -V, --version        Print version and exit.
 END
 }
 
-time_to_seconds() {
-    # $1: formated time string
-    if echo "${1}" | grep -E -q '^([0-9]+[wdhms])+$'; then
-        echo "${1}" | sed 's/w/ * 604800 + /g; s/d/ * 86400 + /g; s/h/ * 3600 + /g; s/m/ * 60 + /g; s/s/ + /g; s/+ $//' | xargs expr
-    elif echo "${1}" | grep -E -q '^([0-9]+$)'; then
-        echo "${1} * 3600" | xargs expr
-    else
-        return 1
-    fi
-}
-
-delay_from_disable_file() {
-    # $1: disabled file containing the re-enable time in sec
-    enable_secs=$(grep -v -E "^\s*#" "${1}" | grep -E "^[0-9]+$" | head -n1 | awk '{print $1}')
-    # If file is empty, use file last change date plus default disabled time
-    if [ -z "${enable_secs}" ]; then
-        file_last_change_secs=$(stat -c %Z "$1")
-        default_disabled_time_secs="$(time_to_seconds "${default_disabled_time}")"
-        enable_secs="$(( file_last_change_secs + default_disabled_time_secs))"
-    fi
-
-    now_secs=$(date +"%s")
-    echo $(( enable_secs - now_secs ))
-}
-
-delay_to_string() {
-    #$1 delay in secs
-    delay_days="$(( delay /86400 ))"
-    if [ "${delay_days}" -eq 0 ]; then delay_days=""
-    else delay_days="${delay_days}d"; fi
-
-    delay_hours="$(( (delay %86400) /3600 ))"
-    if [ "${delay_hours}" -eq 0 ]; then delay_hours=""
-    else delay_hours="${delay_hours}h"; fi
-
-    delay_minutes="$(( ((delay %86400) %3600) /60 ))"
-    if [ "${delay_minutes}" -eq 0 ]; then delay_minutes=""
-    else delay_minutes="${delay_minutes}m"; fi
-
-    delay_seconds="$(( ((delay %86400) %3600) %60 ))"
-    if [ "${delay_seconds}" -eq 0 ]; then delay_seconds=""
-    else delay_seconds="${delay_seconds}s"; fi
-
-    echo "${delay_days}${delay_hours}${delay_minutes}${delay_seconds}"
-}
-
-is_disabled() {
-    # $1: disabled file containing the re-enable time in sec
-    if [ -e "$1" ]; then
-        delay=$(delay_from_disable_file "$1")
-        if [ "${delay}" -le "0" ]; then
-            echo "False"
-            enable_check "${check_name}"
-        else
-            echo "True"
-        fi
-    else
-        echo False
-    fi
-}
-
-enable_check() {
-    # $1: check name
+function enable_wrapper() {
+    # $1: wrapper name
     if [ "$(id -u)" -eq "0" ] ; then
-        /usr/local/bin/alerts_switch enable "$1"
+        /usr/local/bin/alerts_switch enable "${1}"
     else
-        sudo /usr/local/bin/alerts_switch enable "$1"
+        sudo /usr/local/bin/alerts_switch enable "${1}"
     fi
 }
 
-main() {
-    is_disabled=$(is_disabled "${disable_file}")
+function main() {
+    is_disabled="$(is_disabled "${wrapper_name}")"
+
+    if [ -e "${disable_file}" ] && [ "${is_disabled}" == "False" ]; then
+        enable_wrapper "${wrapper_name}"
+    fi
 
     timeout_command=""
     if [ "${is_disabled}" == "True" ]; then
         timeout_command="timeout 9"
     fi
 
-    check_stdout=$(${timeout_command} ${check_command})
+    check_stdout="$(${timeout_command} ${check_command})"
     check_rc=$?
 
     if [ "${is_disabled}" == "True" ] && [ "${check_rc}" -eq 124 ] && [ -z "${check_stdout}" ]; then
@@ -128,9 +61,11 @@ main() {
     fi
 
     if [ "${is_disabled}" == "True" ]; then
-        delay=$(delay_from_disable_file "${disable_file}")
-        delay_str="$(delay_to_string "${delay}")"
-        echo "ALERT DISABLED until ${delay_str} - ${check_stdout}"
+        enable_time="$(get_enable_time "${wrapper_name}")"
+        enable_delay="$(enable_delay "${enable_time}")"
+        delay_str="$(delay_to_string "${enable_delay}")"
+        enable_date="$(date --date "+${enable_delay} seconds" "+%d %h %Y at %H:%M:%S")"
+        echo "ALERT DISABLED until ${enable_date} (${delay_str} left) - ${check_stdout}"
     else
         echo "${check_stdout}"
     fi
@@ -151,7 +86,7 @@ if [[ "${1}" =~ -.* ]]; then
     # parse options
     # based on https://gist.github.com/deshion/10d3cb5f88a21671e17a
     while :; do
-        case $1 in
+        case "${1}" in
             -h|-\?|--help)
                 show_help
                 exit 0
@@ -162,22 +97,22 @@ if [[ "${1}" =~ -.* ]]; then
                 ;;
             -n|--name)
                 # with value separated by space
-                if [ -n "$2" ]; then
-                    check_name=$2
+                if [ -n "${2}" ]; then
+                    wrapper_name="${2}"
                     shift
                 else
                     printf 'ERROR: "--name" requires a non-empty option argument.\n' >&2
-                    exit 1
+                    exit 2
                 fi
                 ;;
             -n|--name=?*)
                 # with value separated by =
-                check_name=${1#*=}
+                wrapper_name="${1#*=}"
                 ;;
             -n|--name=)
                 # without value
                 printf 'ERROR: "--name" requires a non-empty option argument.\n' >&2
-                exit 1
+                exit 2
                 ;;
             --)
                 # End of all options.
@@ -186,8 +121,8 @@ if [[ "${1}" =~ -.* ]]; then
                 ;;
             -?*)
                 # ignore unknown options
-                printf 'WARN: Unknown option : %s\n' "$1" >&2
-                exit 1
+                printf 'ERROR: Unknown option : %s\n' "${1}" >&2
+                exit 2
                 ;;
             *)
                 # Default case: If no more options then break out of the loop.
@@ -201,27 +136,26 @@ if [[ "${1}" =~ -.* ]]; then
     check_command="$*"
 else
     # no option is passed (backward compatibility with previous version)
-    # treat the first argument as check_name and the rest as the command
-    check_name="${1}"
+    # treat the first argument as wrapper_name and the rest as the command
+    wrapper_name="${1}"
     shift
     check_command="$*"
 fi
 
-if [ -z "${check_name}" ]; then
-    printf 'ERROR: You must specify a check name, with --names.\n' >&2
+if [ -z "${wrapper_name}" ]; then
+    printf 'ERROR: You must specify a wrapper name, with --names.\n' >&2
     exit 2
 fi
 if [ -z "${check_command}" ]; then
     printf 'ERROR: You must specify a command to execute.\n' >&2
     exit 2
 fi
-if [ -e "${base_dir}" ] && [ ! -x "${base_dir}" ]; then
-    printf "ERROR: %s exists but is no reachable.\n" "${base_dir}"
+if [ -e "${var_dir}" ] && [ ! -x "${var_dir}" ]; then
+    printf "ERROR: %s exists but is no reachable.\n" "${var_dir}"
     exit 2
 fi
 
-readonly check_name
-readonly check_command
-readonly disable_file="${base_dir}/${check_name}_alerts_disabled"
+disable_file="$(get_disable_file_path "${wrapper_name}")"
+readonly wrapper_name check_command disable_file
 
 main
