supervisord: improve NRPE check

diff --git a/nagios-nrpe/files/plugins/check_supervisord b/nagios-nrpe/files/plugins/check_supervisord
--- a/nagios-nrpe/files/plugins/check_supervisord
+++ b/nagios-nrpe/files/plugins/check_supervisord
@@ -1,21 +1,41 @@
 #!/bin/bash
 
-n_running=0
-n_total=0
+if [ ! -d /etc/supervisor/conf.d/ ]; then
+    echo "UNKNOWN: /etc/supervisor/conf.d/ not found. Is supervisord installed?"
+    exit 3
+fi
+
+for file in $(find /etc/supervisor/conf.d/ -type f); do
+    unknown=0
+    if [ ! -r "${file}" ]; then
+        echo "UNKNOWN: $file not readable. Please run chmod a+r on this file."
+        unknown=$((unknown + 1))
+    fi  
+    if [ "${unknown}" -ne 0 ]; then
+        exit 3
+    fi  
+done
+
+numprocs_expected=$(grep --recursive --no-messages --no-filename --only-matching --extended-regexp 'numprocs=([0-9]+)' /etc/supervisor/conf.d/ | awk -F'=' '{ sum+=$2; } END{ print sum }')
+
+if [ -z "${numprocs_expected}" ]; then
+    numprocs_expected=0
+fi
+
+numprocs_running=0
 
 while read line; do
-    n_total=$((n_total+1))
     if echo "${line}" |grep -qs RUNNING; then
-        n_running=$((n_running+1))
-    fi
+        numprocs_running=$((numprocs_running + 1))
+    fi  
 done <<< $(sudo /usr/bin/supervisorctl status)
 
-if [ "${n_total}" -eq 0 ] || [ "${n_total}" -ne "${n_running}" ]; then
-    echo "CRITICAL - ${n_running}/${n_total} running"
+if [ "${numprocs_expected}" -eq 0 ] || [ "${numprocs_expected}" -ne "${numprocs_running}" ]; then
+    echo "CRITICAL - ${numprocs_running}/${numprocs_expected} running"
     sudo /usr/bin/supervisorctl status
-    #exit 2
+    exit 2
 else
-    echo "OK - ${n_running}/${n_total} running"
+    echo "OK - ${numprocs_running}/${numprocs_expected} running"
     sudo /usr/bin/supervisorctl status
 fi
 
