evodomains: Rename domains to evodomains.

diff --git a/nagios-nrpe/files/plugins/check_domains b/nagios-nrpe/files/plugins/check_domains
--- a/nagios-nrpe/files/plugins/check_domains
+++ b/nagios-nrpe/files/plugins/check_domains
@@ -5,10 +5,10 @@
 # Written by Will
 #
 
-if ! command -v domains >/dev/null; then
-    echo 'UNKNOWN - Missing dependency domains.'
+if ! command -v evodomains >/dev/null; then
+    echo 'UNKNOWN - Missing dependency evodomains.'
     exit 3
 fi
 
-domains -o nrpe -a check-dns
+evodomains -o nrpe -a check-dns
 
